
#backend web application, scale this with docker-compose scale web=3
# web:
#     image: liberalman/helloworld:latest
#     environment:
#       SERVICE_80_NAME: my-web-server
#       SERVICE_TAGS: my-web-server
#       MY_HOST: my-web-server
#     # ports:
#     # - "80:80"

mywebapp:
    image: node:latest
    environment:
        SERVICE_NAME: pos-calc-api
        SERVICE_TAGS: pos-calc-api
        SERVICE_IP: 192.168.2.119
    volumes:
        - ./pos-calc-api:/app/pos-calc-api
    working_dir: /app/pos-calc-api/
    ports:
        - "8180"
    # restart: always
    command: ["/bin/sh", "-c", "export NODE_ENV=prd&&node app.js"]

# listen on local docker sock to register the container with public ports to the consul service
registrator:
    image: gliderlabs/registrator:latest
    hostname: registrator
    volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
    command: -ip=192.168.2.119 consul://192.168.2.121:8500


# docker-compose scale web=3    